/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itq.isc.soa.validacionsat;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author diazn
 */
public class PantallaInicial extends javax.swing.JFrame {
    
    String nombreArchivo = "";
    File[] ficherosXML = null;
    String ubicacionCarpetaExcel = "";

    /**
     * Creates new form PantallaInicial
     */
    public PantallaInicial() {
        initComponents();
    }
    
    public void crearArchivoNuevo() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int seleccion = fileChooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            System.out.println(" directorio: " + fichero.getAbsolutePath());
            this.jtUbicacionCarpertaResultadoExcelXML.setText(fichero.getAbsolutePath());
            ubicacionCarpetaExcel = fichero.getName();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAConsola = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTBExcel = new javax.swing.JToggleButton();
        jTBArchivoExcel = new javax.swing.JToggleButton();
        jTBLimpiar = new javax.swing.JToggleButton();
        jtUbicacionXml = new javax.swing.JTextField();
        jTBSelectorArchivosXML = new javax.swing.JToggleButton();
        jtUbicacionCarpertaResultadoExcelXML = new javax.swing.JTextField();
        jTBIniciarValidacionXML = new javax.swing.JToggleButton();
        jTBSeleccionarCarpetaExcel = new javax.swing.JToggleButton();
        jtUbicacionArchivoExcel = new javax.swing.JTextField();
        jCBViaXML = new javax.swing.JCheckBox();
        jCBViaExcel = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO ISC - SOA 2023");
        setResizable(false);

        jTAConsola.setColumns(20);
        jTAConsola.setLineWrap(true);
        jTAConsola.setRows(5);
        jTAConsola.setAutoscrolls(false);
        jTAConsola.setDoubleBuffered(true);
        jTAConsola.setDragEnabled(true);
        jScrollPane1.setViewportView(jTAConsola);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jTBExcel.setText("Iniciar Validacion Excel");
        jTBExcel.setEnabled(false);
        jTBExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBExcelActionPerformed(evt);
            }
        });

        jTBArchivoExcel.setText("Seleccionar Archivo Excel");
        jTBArchivoExcel.setToolTipText("");
        jTBArchivoExcel.setEnabled(false);
        jTBArchivoExcel.setFocusPainted(false);
        jTBArchivoExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBArchivoExcelActionPerformed(evt);
            }
        });

        jTBLimpiar.setText("Limpiar consola");
        jTBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBLimpiarActionPerformed(evt);
            }
        });

        jtUbicacionXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUbicacionXmlActionPerformed(evt);
            }
        });

        jTBSelectorArchivosXML.setText("Seleccionar Archivos CFDI XML");
        jTBSelectorArchivosXML.setToolTipText("");
        jTBSelectorArchivosXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBSelectorArchivosXMLActionPerformed(evt);
            }
        });

        jtUbicacionCarpertaResultadoExcelXML.setText("D:\\");
            jtUbicacionCarpertaResultadoExcelXML.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jtUbicacionCarpertaResultadoExcelXMLActionPerformed(evt);
                }
            });

            jTBIniciarValidacionXML.setText("Iniciar Validacion XML");
            jTBIniciarValidacionXML.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTBIniciarValidacionXMLActionPerformed(evt);
                }
            });

            jTBSeleccionarCarpetaExcel.setText("Seleccionar carpeta para alojamiento de  Excel");
            jTBSeleccionarCarpetaExcel.setToolTipText("");
            jTBSeleccionarCarpetaExcel.setFocusPainted(false);
            jTBSeleccionarCarpetaExcel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTBSeleccionarCarpetaExcelActionPerformed(evt);
                }
            });

            jtUbicacionArchivoExcel.setEnabled(false);
            jtUbicacionArchivoExcel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jtUbicacionArchivoExcelActionPerformed(evt);
                }
            });

            jCBViaXML.setSelected(true);
            jCBViaXML.setText("Validacion via CFDI XML");
            jCBViaXML.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCBViaXMLActionPerformed(evt);
                }
            });

            jCBViaExcel.setText("Validacion via Excel");
            jCBViaExcel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCBViaExcelActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtUbicacionXml, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                                .addComponent(jtUbicacionCarpertaResultadoExcelXML)))
                        .addComponent(jtUbicacionArchivoExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTBSeleccionarCarpetaExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTBArchivoExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTBExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTBSelectorArchivosXML, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTBIniciarValidacionXML, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCBViaXML, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCBViaExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBViaXML)
                        .addComponent(jCBViaExcel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTBSelectorArchivosXML, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTBIniciarValidacionXML))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jtUbicacionXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTBSeleccionarCarpetaExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jtUbicacionCarpertaResultadoExcelXML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTBArchivoExcel)
                        .addComponent(jTBExcel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jtUbicacionArchivoExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTBLimpiar))
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTBArchivoExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBArchivoExcelActionPerformed
        crearArchivoNuevo();
    }//GEN-LAST:event_jTBArchivoExcelActionPerformed

    private void jtUbicacionCarpertaResultadoExcelXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUbicacionCarpertaResultadoExcelXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUbicacionCarpertaResultadoExcelXMLActionPerformed

    private void jTBExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBExcelActionPerformed
        ValidacionSAT validador = new ValidacionSAT(this.jtUbicacionCarpertaResultadoExcelXML.getText(), this);
        validador.validarExcel(this.jtUbicacionCarpertaResultadoExcelXML.getText());
    }//GEN-LAST:event_jTBExcelActionPerformed

    private void jTBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBLimpiarActionPerformed
        this.jTAConsola.setText("");
    }//GEN-LAST:event_jTBLimpiarActionPerformed

    private void jTBSelectorArchivosXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBSelectorArchivosXMLActionPerformed
//        JFileChooser fileChooser = new JFileChooser();
//        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
//        int seleccion = fileChooser.showOpenDialog(null);
//        if (seleccion == JFileChooser.APPROVE_OPTION) {
//            File fichero = fileChooser.getSelectedFile();
//            System.out.println(" directorio: " + fichero.getAbsolutePath());
//            this.jtUbicacionArchivo.setText(fichero.getAbsolutePath());
//            nombreArchivo = fichero.getName();
//        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setMultiSelectionEnabled(true); // Habilita la selección múltiple de archivos

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos XML", "xml");
        fileChooser.setFileFilter(filter);
        // Eliminar la opción "Todos los archivos" (All Files)
        fileChooser.removeChoosableFileFilter(fileChooser.getAcceptAllFileFilter());
        
        int seleccion = fileChooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            ficherosXML = fileChooser.getSelectedFiles();
            for (File fichero : ficherosXML) {
                System.out.println("Archivo seleccionado: " + fichero.getAbsolutePath());
                // Puedes hacer lo que necesites con cada archivo, por ejemplo:
                // this.jtUbicacionArchivo.setText(fichero.getAbsolutePath());
                // nombreArchivo = fichero.getName();
            }
            if (ficherosXML != null) {
                this.jtUbicacionXml.setText("NUMERO DE ARCHIVOS XML SELECCIONADOS = " + ficherosXML.length);
            }
        }
    }//GEN-LAST:event_jTBSelectorArchivosXMLActionPerformed

    private void jtUbicacionXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUbicacionXmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUbicacionXmlActionPerformed

    private void jTBIniciarValidacionXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBIniciarValidacionXMLActionPerformed
        if (jtUbicacionCarpertaResultadoExcelXML == null) {
            jTAConsola.setText("LA UBICACION DE LA CARPETA DONDE SE ALMACENARA EL EXCEL NO PUEDE SER NULA");
            return;
        }
        if (jtUbicacionCarpertaResultadoExcelXML.getText().equals("")) {
            jTAConsola.setText("LA UBICACION DE LA CARPETA DONDE SE ALMACENARA EL EXCEL NO PUEDE SER NULA");
            return;
        }
        ValidacionSAT validador = new ValidacionSAT(this);
        jTAConsola.setText("");
        validador.validacionYCargaArchivosXML(ficherosXML, jtUbicacionCarpertaResultadoExcelXML.getText());
    }//GEN-LAST:event_jTBIniciarValidacionXMLActionPerformed

    private void jTBSeleccionarCarpetaExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBSeleccionarCarpetaExcelActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = fileChooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            System.out.println("directorio: " + fichero.getAbsolutePath());
            this.jtUbicacionCarpertaResultadoExcelXML.setText(fichero.getAbsolutePath());
            ubicacionCarpetaExcel = fichero.getName();
        }
    }//GEN-LAST:event_jTBSeleccionarCarpetaExcelActionPerformed

    private void jtUbicacionArchivoExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUbicacionArchivoExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUbicacionArchivoExcelActionPerformed

    private void jCBViaXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBViaXMLActionPerformed
        if (jCBViaXML.isSelected()) {
            jCBViaExcel.setSelected(false);
            jTBSelectorArchivosXML.setEnabled(true);
            jTBIniciarValidacionXML.setEnabled(true);
            jtUbicacionXml.setEnabled(true);
            jtUbicacionXml.setText("");
            jTBSeleccionarCarpetaExcel.setEnabled(true);
            jtUbicacionCarpertaResultadoExcelXML.setEnabled(true);
            jtUbicacionCarpertaResultadoExcelXML.setText("");
            jTBArchivoExcel.setEnabled(false);
            jTBExcel.setEnabled(false);
            jtUbicacionArchivoExcel.setEnabled(false);
            jtUbicacionArchivoExcel.setText("");
            
        }
    }//GEN-LAST:event_jCBViaXMLActionPerformed

    private void jCBViaExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBViaExcelActionPerformed
        if (jCBViaExcel.isSelected()) {
            jCBViaXML.setSelected(false);
            jTBSelectorArchivosXML.setEnabled(false);
            jTBIniciarValidacionXML.setEnabled(false);
            jtUbicacionXml.setEnabled(false);
            jtUbicacionXml.setText("");
            jTBSeleccionarCarpetaExcel.setEnabled(false);
            jtUbicacionCarpertaResultadoExcelXML.setEnabled(false);
            jtUbicacionCarpertaResultadoExcelXML.setText("");
            jTBArchivoExcel.setEnabled(true);
            jTBExcel.setEnabled(true);
            jtUbicacionArchivoExcel.setEnabled(true);
            jtUbicacionArchivoExcel.setText("");
            
        }
    }//GEN-LAST:event_jCBViaExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }
    
    public void escribirConsola(String mesajeNuevo) {
        mesajeNuevo = this.jTAConsola.getText() + "\r\n" + mesajeNuevo;
        this.jTAConsola.setText(mesajeNuevo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCBViaExcel;
    private javax.swing.JCheckBox jCBViaXML;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAConsola;
    private javax.swing.JToggleButton jTBArchivoExcel;
    private javax.swing.JToggleButton jTBExcel;
    private javax.swing.JToggleButton jTBIniciarValidacionXML;
    private javax.swing.JToggleButton jTBLimpiar;
    private javax.swing.JToggleButton jTBSeleccionarCarpetaExcel;
    private javax.swing.JToggleButton jTBSelectorArchivosXML;
    private javax.swing.JTextField jtUbicacionArchivoExcel;
    private javax.swing.JTextField jtUbicacionCarpertaResultadoExcelXML;
    private javax.swing.JTextField jtUbicacionXml;
    // End of variables declaration//GEN-END:variables
}
